import { slugify as defaultSlugify } from '@mdit-vue/shared'
import { escapeHtml } from '@mdit/helper'
import { field as fieldPlugin } from '@mdit/plugin-field'
import type {
  FieldMeta,
  MarkdownItFieldOpenRenderer,
  MarkdownItFieldOptions,
} from '@mdit/plugin-field'
import { ensureLeadingSlash } from '@vuepress/helper'
import type { PluginWithOptions } from 'markdown-it'
import type { MarkdownEnv } from 'vuepress/markdown'
import { resolveLocalePath } from 'vuepress/shared'

import type {
  MarkdownFieldPluginLocaleConfig,
  MarkdownFieldPluginLocaleData,
} from './options.js'

const DEFAULT_LOCALE: MarkdownFieldPluginLocaleData = {
  default: 'Default',
  required: 'Required',
  optional: 'Optional',
  deprecated: 'Deprecated',
}

/**
 * Token type of a field item, generated by `@mdit/plugin-field` with the
 * default `fields` container name
 */
const FIELD_ITEM_TOKEN = 'fields_field_open'

/**
 * Options for the field markdown-it plugin
 *
 * 字段 markdown-it 插件选项
 */
export interface FieldPluginOptions {
  /**
   * Locale config
   *
   * 国际化配置
   */
  locales?: MarkdownFieldPluginLocaleConfig

  /**
   * Slugify function to generate ids for field items
   *
   * 为字段项生成 id 的 slugify 函数
   *
   * @default defaultSlugify
   */
  slugify?: (str: string) => string
}

const escape = (value: string | true): string =>
  value === true ? '' : escapeHtml(value)

const resolveFieldLocale = (
  options: MarkdownFieldPluginLocaleConfig,
  env: MarkdownEnv,
): MarkdownFieldPluginLocaleData => {
  const relativePath = ensureLeadingSlash(env.filePathRelative ?? '')
  const localePath = resolveLocalePath(options, relativePath)

  return options[localePath] ?? DEFAULT_LOCALE
}

/**
 * Field container markdown-it plugin
 *
 * 字段容器 markdown-it 插件
 *
 * @param md - MarkdownIt instance / MarkdownIt 实例
 * @param options - Plugin options / 插件选项
 */
export const field: PluginWithOptions<FieldPluginOptions> = (
  md,
  { locales = {}, slugify = defaultSlugify } = {},
) => {
  const fieldOpenRenderer: MarkdownItFieldOpenRenderer = (
    { details, name },
    tokens,
    index,
    _options,
    env: MarkdownEnv,
  ) => {
    const locale = resolveFieldLocale(locales, env)
    const classNames = ['vp-field']
    const badges: string[] = []
    let type = ''
    let defaultValue = ''

    for (const { attr, quote, value } of details) {
      if (attr === 'type') {
        type = `<code class="vp-field-type">${escape(value)}</code>\n`
      } else if (attr === 'default') {
        defaultValue = `\
<div class="vp-field-default">
<span class="vp-field-default-label">${locale.default}</span>
${quote === 'backtick' ? `<code>${escape(value)}</code>` : md.renderInline(escape(value))}
</div>
`
      } else if (
        attr === 'required' ||
        attr === 'optional' ||
        attr === 'deprecated'
      ) {
        if (attr === 'deprecated') classNames.push('deprecated')
        badges.push(`<span class="vp-field-${attr}">${locale[attr]}</span>\n`)
      } else {
        badges.push(
          `<span class="vp-field-attr">${attr}: ${escape(value)}</span>\n`,
        )
      }
    }

    const badgesHtml = badges.length
      ? `\
<span class="vp-field-badges">
  ${badges.join('\n  ')}\
</span>
`
      : ''

    const id = tokens[index].attrGet('id')
    const idAttr = id ? ` id="${escapeHtml(id)}"` : ''

    return `\
<div class="${classNames.join(' ')}">
<div class="vp-field-header">
<span class="vp-field-name"${idAttr}>${escapeHtml(name)}</span>
${badgesHtml}${type}\
</div>
${defaultValue}\
<div class="vp-field-description">
`
  }

  md.use<MarkdownItFieldOptions>(fieldPlugin, {
    fieldsOpenRenderer: () => '<div class="vp-fields">\n',
    fieldsCloseRenderer: () => '</div>\n',
    fieldOpenRenderer,
    fieldCloseRenderer: () => '</div>\n</div>\n',
  })

  // Add unique ids to field items so that they can be linked to
  md.core.ruler.push('markdown-field-id', (state) => {
    const slugs: Record<string, boolean> = {}

    // Reserve ids that are already used in the page (e.g. headings) to avoid duplicates
    for (const token of state.tokens) {
      const id = token.attrGet('id')

      if (id) slugs[id] = true
    }

    for (const token of state.tokens) {
      if (token.type !== FIELD_ITEM_TOKEN) continue

      const { name } = token.meta as FieldMeta
      const base = slugify(name) || 'field'

      let slug = base
      let index = 1

      while (Object.hasOwn(slugs, slug)) {
        slug = `${base}-${index}`
        index += 1
      }

      slugs[slug] = true
      token.attrSet('id', slug)
    }
  })
}
