extends:
  - stylelint-config-hope

ignoreFiles:
  - .cache/
  - .temp/
  - '**/__fixtures__/**'
  - node_modules/
  - '**/lib/**/'
  - '**/*.module.scss'
  - '**/empty.scss'

rules:
  media-feature-range-notation: prefix
  no-descending-specificity: null
  # workaround for mixed-declarations
  no-duplicate-selectors: null
  declaration-block-no-redundant-longhand-properties:
    - true
    - ignoreShorthands:
        - 'margin-block'
        - 'margin-inline'
        - 'padding-inline'
        - 'padding-block'

overrides:
  - files:
      - '**/*.html'
    extends:
      - stylelint-config-html/html

  - files:
      - '**/*.vue'
    extends:
      - stylelint-config-html/vue

    rules:
      function-no-unknown:
        - true
        - ignoreFunctions:
            - v-bind

      selector-pseudo-class-no-unknown:
        - true

        - ignorePseudoClasses:
            - deep
            - global
            - slotted

      selector-pseudo-element-no-unknown:
        - true
        - ignorePseudoElements:
            - v-deep
            - v-global
            - v-slotted
