packages:
  - docs/
  - e2e/
  - plugins/*/*
  - themes/*
  - tools/*
  - docs-next/
catalog:
  '@vuepress/bundler-vite': 2.0.0-rc.20
  '@vuepress/bundler-webpack': 2.0.0-rc.20
  vuepress: 2.0.0-rc.20
