packages:
  - docs/
  - e2e/
  - plugins/*/*
  - themes/*
  - tools/*

catalog:
  '@vuepress/bundler-vite': 2.0.0-rc.23
  '@vuepress/bundler-webpack': 2.0.0-rc.23
  '@vueuse/core': ^13.3.0
  sass: ^1.89.2
  sass-embedded: ^1.89.2
  sass-loader: ^16.0.5
  vue: ^3.5.16
  vuepress: 2.0.0-rc.23

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver

overrides:
  esbuild: ^0.25.4

peerDependencyRules:
  allowedVersions:
    artalk>marked: ^15.0.0
