packages:
  - docs/
  - e2e/
  - plugins/*/*
  - themes/*
  - tools/*

catalog:
  '@vuepress/bundler-vite': 2.0.0-rc.26
  '@vuepress/bundler-webpack': 2.0.0-rc.26
  '@vueuse/core': ^13.9.0
  chokidar: ^4.0.3
  sass: ^1.93.2
  sass-embedded: ^1.93.2
  sass-loader: ^16.0.6
  vue: ^3.5.22
  vuepress: 2.0.0-rc.26

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver

overrides:
  esbuild: ^0.25.6

peerDependencyRules:
  allowedVersions:
    artalk>marked: ^16.0.0
