packages:
  - docs/
  - e2e/
  - plugins/*/*
  - themes/*
  - tools/*

catalog:
  '@vuepress/bundler-vite': 2.0.0-rc.24
  '@vuepress/bundler-webpack': 2.0.0-rc.24
  '@vueuse/core': ^13.7.0
  chokidar: ^4.0.3
  sass: ^1.90.0
  sass-embedded: ^1.90.0
  sass-loader: ^16.0.5
  vue: ^3.5.19
  vuepress: 2.0.0-rc.24

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver

overrides:
  esbuild: ^0.25.6

peerDependencyRules:
  allowedVersions:
    artalk>marked: ^16.0.0
