packages:
  - docs/
  - e2e/
  - plugins/*/*
  - themes/*
  - tools/*

catalog:
  '@vuepress/bundler-vite': 2.0.0-rc.31
  '@vuepress/bundler-webpack': 2.0.0-rc.31
  '@vueuse/core': ^14.4.0
  chokidar: ^5.0.0
  sass: ^1.104.0
  sass-embedded: ^1.104.0
  sass-loader: ^17.0.1
  stylelint-config-standard: 40.0.0
  stylelint-config-standard-scss: 17.0.0
  stylelint-order: 8.1.1
  vue: ^3.5.42
  vuepress: 2.0.0-rc.31

catalogMode: prefer

allowBuilds:
  '@parcel/watcher': true
  esbuild: true

minimumReleaseAgeExclude:
  - '@oxfmt/*'
  - '@oxlint/*'
  - '@vue/*'
  - '@vuepress/*'
  - '@vitest/*'
  - oxc-config-hope
  - oxfmt
  - oxlint
  - vite
  - vitest
  - vue
  - vuepress

packageExtensions:
  stylelint:
    peerDependencies:
      postcss-html: ^1.8.1
    peerDependenciesMeta:
      postcss-html:
        optional: true

peerDependencyRules:
  allowedVersions:
    artalk>marked: ^18.0.0
    echarts-wordcloud>echarts: ^6.0.0

cleanupUnusedCatalogs: true

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 720

patchedDependencies:
  '@vuepress/bundler-webpack': patches/@vuepress__bundler-webpack.patch
