packages:
  - docs/
  - e2e/
  - plugins/*/*
  - themes/*
  - tools/*

catalog:
  '@vueuse/core': ^12.2.0
  '@vuepress/bundler-vite': 2.0.0-rc.19
  '@vuepress/bundler-webpack': 2.0.0-rc.19
  chokidar: ^3.6.0
  rollup: ^4.29.1
  sass-embedded: ^1.83.0
  sass-loader: ^16.0.4
  vue: ^3.5.13
  vuepress: 2.0.0-rc.19
