/**
 * Icons matched by a part of the name of a file
 *
 * 根据文件名称的一部分匹配的图标
 */
export const partials: Record<string, string> = {
  'Gemfile': 'vscode-icons:file-type-ruby',
  'gemfile': 'vscode-icons:file-type-ruby',
  'dockerfile': 'vscode-icons:file-type-docker',
  'Dockerfile': 'vscode-icons:file-type-docker',
  'DOCKERFILE': 'vscode-icons:file-type-docker',
  '.dockerignore': 'vscode-icons:file-type-docker',
  'docker-healthcheck': 'vscode-icons:file-type-docker',
  'docker-compose.yml': 'vscode-icons:file-type-docker',
  'docker-compose.yaml': 'vscode-icons:file-type-docker',
  'docker-compose.override.yml': 'vscode-icons:file-type-docker',
  'docker-compose.override.yaml': 'vscode-icons:file-type-docker',
  'GULPFILE': 'vscode-icons:file-type-gulp',
  'Gulpfile': 'vscode-icons:file-type-gulp',
  'gulpfile': 'vscode-icons:file-type-gulp',
  'gulpfile.js': 'vscode-icons:file-type-gulp',
  'LICENSE': 'vscode-icons:file-type-license',
  'LICENCE': 'vscode-icons:file-type-license',
  'LICENSE.txt': 'vscode-icons:file-type-license',
  'LICENCE.txt': 'vscode-icons:file-type-license',
  'LICENSE.md': 'vscode-icons:file-type-license',
  'LICENCE.md': 'vscode-icons:file-type-license',
  'COPYING': 'vscode-icons:file-type-license',
  'COPYING.txt': 'vscode-icons:file-type-license',
  'COPYING.md': 'vscode-icons:file-type-license',
  'COMPILING': 'vscode-icons:file-type-license',
  'COMPILING.txt': 'vscode-icons:file-type-license',
  'COMPILING.md': 'vscode-icons:file-type-license',
  'CONTRIBUTING': 'vscode-icons:file-type-license',
  'CONTRIBUTING.txt': 'vscode-icons:file-type-license',
  'CONTRIBUTING.md': 'vscode-icons:file-type-license',
  'MAKEFILE': 'vscode-icons:file-type-makefile',
  'Makefile': 'vscode-icons:file-type-makefile',
  'makefile': 'vscode-icons:file-type-makefile',
  'QMAKEFILE': 'vscode-icons:file-type-makefile',
  'QMakefile': 'vscode-icons:file-type-makefile',
  'qmakefile': 'vscode-icons:file-type-makefile',
  'OMAKEFILE': 'vscode-icons:file-type-makefile',
  'OMakefile': 'vscode-icons:file-type-makefile',
  'omakefile': 'vscode-icons:file-type-makefile',
  'CMAKELISTS.TXT': 'vscode-icons:file-type-makefile',
  'CMAKELISTS.txt': 'vscode-icons:file-type-makefile',
  'CMakeLists.txt': 'vscode-icons:file-type-makefile',
  'cmakelists.txt': 'vscode-icons:file-type-makefile',
  'Procfile': 'vscode-icons:file-type-procfile',
  'TODO': 'vscode-icons:file-type-light-todo',
  'TODO.txt': 'vscode-icons:file-type-light-todo',
  'TODO.md': 'vscode-icons:file-type-light-todo',
}
