import { mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'

import { TEST_MODULES_KEY } from '../shared/keys.js'
import { getTestModuleFilePath } from './moduleDir.js'

/**
 * Restore function returned by `stubModule()`
 *
 * 由 `stubModule()` 返回的还原函数
 */
export type RestoreStubbedModule = () => void

const globals = globalThis as Record<string, unknown>

const IDENTIFIER_PATTERN = /^[A-Za-z_$][\w$]*$/u

/**
 * Get the global registry of the values of the stubbed modules
 *
 * The generated module reads this registry at evaluation time, in the Vitest
 * worker, so that every test can stub the value of a module.
 *
 * 获取被 stub 模块的值的全局注册表
 *
 * 生成模块会在求值时（Vitest worker 中）读取该注册表，因此每个测试都能 stub 模块的值。
 *
 * @returns The registry / 注册表
 */
export const getStubbedModules = (): Record<string, Record<string, unknown>> =>
  (globals[TEST_MODULES_KEY] ??= {}) as Record<string, Record<string, unknown>>

const createModuleSource = (
  id: string,
  moduleExports: Record<string, unknown>,
): string => {
  const names = Object.keys(moduleExports).filter((name) => name !== 'default')

  for (const name of names) {
    if (!IDENTIFIER_PATTERN.test(name)) {
      throw new Error(
        `[vuepress/test-utils] The stub of "${id}" has the export "${name}", which is not a valid identifier. Only identifiers and "default" are supported.`,
      )
    }
  }

  return [
    `const __module = (globalThis[${JSON.stringify(TEST_MODULES_KEY)}] ?? {})[${JSON.stringify(id)}]`,
    `if (__module === undefined) {`,
    `  throw new Error(${JSON.stringify(
      `[vuepress/test-utils] The module "${id}" is imported but has not been stubbed. Call stubModule(${JSON.stringify(id)}, ...) before importing the module that uses it.`,
    )})`,
    `}`,
    ...names.map(
      (name) => `export const ${name} = __module[${JSON.stringify(name)}]`,
    ),
    `export default __module["default"]`,
    ``,
  ].join('\n')
}

/**
 * Stub a generated (virtual) client module
 *
 * VuePress generates client modules at build time: `@internal/*` modules, and
 * `@temp/*` modules created by generated client configs (e.g.
 * `@temp/revealjs/index.js`). They do not exist in a unit test, so a module
 * that imports them cannot be imported at all.
 *
 * `stubModule()` registers the given values on `globalThis`, and writes a
 * generated ESM module that re-exports them. The Vite plugin of this package
 * resolves the module id to that generated file, so the import works in both
 * the `node` and the `happy-dom` environment.
 *
 * Notice that Vite resolves imports when a module is transformed, which happens
 * before the test runs. Therefore the module that imports the stubbed module
 * must be imported dynamically after `stubModule()`, with `vi.resetModules()`
 * when it may already be cached.
 *
 * 为生成的（虚拟）客户端模块打桩
 *
 * VuePress 会在构建期生成客户端模块：`@internal/*` 模块，以及由生成的客户端配置创建的 `@temp/*` 模块（如
 * `@temp/revealjs/index.js`）。它们在单元测试中并不存在，因此导入它们的模块完全无法导入。
 *
 * `stubModule()` 会把给定值注册到 `globalThis`，并写入一个重新导出它们的生成 ESM 模块。本包的 Vite 插件会把该模块
 * id 解析到生成文件，因此在 `node` 与 `happy-dom` 环境下导入都能工作。
 *
 * 注意：Vite 在模块被转换时解析导入，而这发生在测试运行之前。因此导入被打桩模块的模块，必须在 `stubModule()`
 * 之后动态导入，若它可能已被缓存还需配合 `vi.resetModules()`。
 *
 * @example
 *   const restore = stubModule('@internal/noticeOptions', {
 *     NOTICE_OPTIONS: [{ title: 'Notice', content: 'Content' }],
 *   })
 *
 *   vi.resetModules()
 *   const { useNoticeOptions } =
 *     await import('../src/client/composables/index.js')
 *
 *   restore()
 *
 * @param id - The id of the generated module, exactly as it is imported / 生成模块的
 *   id，与导入时的写法完全一致
 * @param moduleExports - The exports of the module, including `default` /
 *   模块的导出值，包含 `default`
 * @returns A function to restore the previous value / 用于还原先前值的函数
 */
export const stubModule = (
  id: string,
  moduleExports: Record<string, unknown>,
): RestoreStubbedModule => {
  const registry = getStubbedModules()
  const previous = Object.hasOwn(registry, id)
    ? { existed: true as const, value: registry[id] }
    : { existed: false as const, value: undefined }

  const filePath = getTestModuleFilePath(id)

  mkdirSync(path.dirname(filePath), { recursive: true })
  writeFileSync(filePath, createModuleSource(id, moduleExports))

  registry[id] = moduleExports

  return () => {
    if (previous.existed) registry[id] = previous.value
    else Reflect.deleteProperty(registry, id)
  }
}

/**
 * Stub the `@temp/<name>/index.js` module of a plugin
 *
 * It is a shortcut of `stubModule()` for the usual shape of the modules
 * generated by a generated client config.
 *
 * 为插件的 `@temp/<name>/index.js` 模块打桩
 *
 * 它是 `stubModule()` 的快捷方式，用于生成客户端配置所产模块的常见形态。
 *
 * @example
 *   const restore = stubTempModule('revealjs', {
 *     useRevealJs: () => Promise.resolve([Reveal]),
 *   })
 *
 * @param name - The name of the generated module, i.e. `<name>` in
 *   `@temp/<name>/index.js` / 生成模块的名称，即 `@temp/<name>/index.js` 中的 `<name>`
 * @param moduleExports - The exports of the module, including `default` /
 *   模块的导出值，包含 `default`
 * @returns A function to restore the previous value / 用于还原先前值的函数
 */
export const stubTempModule = (
  name: string,
  moduleExports: Record<string, unknown>,
): RestoreStubbedModule => stubModule(`@temp/${name}/index.js`, moduleExports)
