// @vitest-environment happy-dom
import { flushPromises } from '@vue/test-utils'
import { mountVuePress, renderVuePress } from '@vuepress/test-utils/client'
import { describe, expect, it, vi } from 'vitest'
import type { Ref } from 'vue'

import { Notice } from '../../src/client/components/Notice.js'
import noticeClientConfig from '../../src/client/config.js'
import { getNoticeOptions } from '../../src/node/getNoticeOptions.js'
import type {
  NoticeAttrOptions,
  NoticeOptions,
} from '../../src/shared/index.js'

// `@internal/noticeOptions` is a module generated by the Node side at build
// time, and does not exist in a unit test. The notice options are passed
// through the composable instead, with the real `getNoticeOptions` transform.
const state = vi.hoisted(
  (): Ref<NoticeAttrOptions[]> =>
    ({ value: [] }) as unknown as Ref<NoticeAttrOptions[]>,
)

vi.mock(
  import('../../src/client/composables/index.js'),
  (): { useNoticeOptions: () => Ref<NoticeAttrOptions[]> } => ({
    useNoticeOptions: () => state,
  }),
)

const resetStorage = (): void => {
  localStorage.clear()
  sessionStorage.clear()
}

const mountNotice = async (
  options: NoticeOptions[],
  mountOptions: Parameters<typeof mountVuePress>[0] = {},
  storage: Record<string, string> = {},
): ReturnType<typeof mountVuePress> => {
  resetStorage()

  for (const [key, value] of Object.entries(storage))
    sessionStorage.setItem(key, value)

  state.value = getNoticeOptions(options)

  return mountVuePress({ rootComponent: Notice, ...mountOptions })
}

describe('notice component', () => {
  it('should render the notice matching the current route', async () => {
    const wrapper = await mountNotice([
      { path: '/', title: 'Notice Title', content: 'Notice Content' },
    ])

    expect(wrapper.find('.vp-notice-wrapper').exists()).toBe(true)
    expect(wrapper.find('.vp-notice-title').text()).toContain('Notice Title')
    expect(wrapper.find('.vp-notice-content').text()).toContain(
      'Notice Content',
    )
  })

  it('should not render a notice when no option matches the route', async () => {
    const wrapper = await mountNotice([
      { path: '/other/', title: 'Notice Title', content: 'Notice Content' },
    ])

    expect(wrapper.find('.vp-notice-wrapper').exists()).toBe(false)
  })

  it('should match the notice with a regexp', async () => {
    const wrapper = await mountNotice(
      [{ match: /^\/guide\//u, title: 'Notice Title', content: 'Content' }],
      { route: '/guide/intro/' },
    )

    expect(wrapper.find('.vp-notice-wrapper').exists()).toBe(true)
  })

  it('should keep the flags of the regexp', async () => {
    const wrapper = await mountNotice(
      [{ match: /^\/GUIDE\//iu, title: 'Notice Title', content: 'Content' }],
      { route: '/guide/intro/' },
    )

    expect(wrapper.find('.vp-notice-wrapper').exists()).toBe(true)
  })

  it('should not match a route that only differs in case for a case-sensitive regexp', async () => {
    const wrapper = await mountNotice(
      [{ match: /^\/GUIDE\//u, title: 'Notice Title', content: 'Content' }],
      { route: '/guide/intro/' },
    )

    expect(wrapper.find('.vp-notice-wrapper').exists()).toBe(false)
  })

  it('should close the notice and remember it in the session storage', async () => {
    const wrapper = await mountNotice([
      { path: '/', title: 'Notice Title', content: 'Notice Content' },
    ])

    await wrapper.find('.close-icon').trigger('click')
    await flushPromises()

    expect(wrapper.find('.vp-notice-wrapper').exists()).toBe(false)
    expect(sessionStorage.getItem('notice:Notice TitleNotice Content')).toBe(
      'true',
    )
  })

  it('should not render a notice that has been closed before', async () => {
    const wrapper = await mountNotice(
      [{ path: '/', title: 'Notice Title', content: 'Notice Content' }],
      {},
      { 'notice:Notice TitleNotice Content': 'true' },
    )

    expect(wrapper.find('.vp-notice-wrapper').exists()).toBe(false)
  })

  it('should remember the notice in the local storage when it shows once', async () => {
    const wrapper = await mountNotice([
      {
        key: 'once',
        path: '/',
        showOnce: true,
        title: 'Notice Title',
        content: 'Notice Content',
      },
    ])

    await wrapper.find('.close-icon').trigger('click')
    await flushPromises()

    expect(localStorage.getItem('notice-once')).toBe('true')
    expect(sessionStorage.getItem('notice-once')).toBeNull()
  })

  it('should not render the close icon when the notice requires confirmation', async () => {
    const wrapper = await mountNotice([
      {
        confirm: true,
        path: '/',
        title: 'Notice Title',
        content: 'Notice Content',
      },
    ])

    expect(wrapper.find('.vp-notice-wrapper').exists()).toBe(true)
    expect(wrapper.find('.close-icon').exists()).toBe(false)
  })

  it('should render a fullscreen mask that closes the notice on click', async () => {
    const wrapper = await mountNotice([
      {
        fullscreen: true,
        path: '/',
        title: 'Notice Title',
        content: 'Notice Content',
      },
    ])

    expect(wrapper.find('.vp-notice-mask').exists()).toBe(true)

    await wrapper.find('.vp-notice-mask').trigger('click')
    await flushPromises()

    expect(wrapper.find('.vp-notice-wrapper').exists()).toBe(false)
  })

  it('should keep the notice open when the mask of a confirmed fullscreen notice is clicked', async () => {
    const wrapper = await mountNotice([
      {
        confirm: true,
        fullscreen: true,
        path: '/',
        title: 'Notice Title',
        content: 'Notice Content',
      },
    ])

    await wrapper.find('.vp-notice-mask').trigger('click')
    await flushPromises()

    expect(wrapper.find('.vp-notice-wrapper').exists()).toBe(true)
  })

  it('should render the actions and close the notice when one is clicked', async () => {
    const wrapper = await mountNotice([
      {
        actions: [{ text: 'Action Text', type: 'primary' }],
        path: '/',
        title: 'Notice Title',
        content: 'Notice Content',
      },
    ])

    const action = wrapper.find('button.vp-notice-footer-action')

    expect(action.text()).toBe('Action Text')
    expect(action.classes()).toContain('primary')

    await action.trigger('click')
    await flushPromises()

    expect(wrapper.find('.vp-notice-wrapper').exists()).toBe(false)
  })

  it('should register the notice as a root component of the client config', async () => {
    resetStorage()
    state.value = getNoticeOptions([
      { path: '/', title: 'Notice Title', content: 'Notice Content' },
    ])

    const wrapper = await mountVuePress({
      clientConfigs: [noticeClientConfig],
      content: 'Page Content',
    })

    expect(wrapper.find('.vp-notice-wrapper').exists()).toBe(true)
  })

  it('should not render the notice during SSR', async () => {
    resetStorage()
    state.value = getNoticeOptions([
      { path: '/', title: 'Notice Title', content: 'Notice Content' },
    ])

    const html = await renderVuePress({ rootComponent: Notice })

    expect(html).not.toContain('vp-notice-wrapper')
  })
})
