describe('blog', () => {
  it('generate type page', () => {
    cy.visit('/article/').get('article').should('have.length.greaterThan', 0)
    cy.visit('/timeline/').get('article').should('have.length.greaterThan', 0)
  })

  it('generate category main page', () => {
    cy.visit('/category/')
      .get('main')
      .should('not.contain', '404')
      .get('.article-wrapper')
      .should('have.length', 1)
      .get('article')
      .should('have.length', 0)
    cy.visit('/tag/')
      .get('main')
      .should('not.contain', '404')
      .get('.article-wrapper')
      .should('have.length', 1)
      .get('article')
      .should('have.length', 0)
  })

  it('generate category item page', () => {
    cy.visit('/category/category-a/')
      .get('article')
      .should('have.length.greaterThan', 0)
    cy.visit('/category/category-b/')
      .get('article')
      .should('have.length.greaterThan', 0)
    cy.visit('/category/category-c/')
      .get('article')
      .should('have.length.greaterThan', 0)
    cy.visit(encodeURI('/category/分类-1/'))
      .get('article')
      .should('have.length.greaterThan', 0)
    cy.visit(encodeURI('/category/分类-2/'))
      .get('article')
      .should('have.length.greaterThan', 0)

    cy.visit(encodeURI('/tag/tag-a/'))
      .get('article')
      .should('have.length.greaterThan', 0)
    cy.visit(encodeURI('/tag/tag-b/'))
      .get('article')
      .should('have.length.greaterThan', 0)
    cy.visit(encodeURI('/tag/tag-c/'))
      .get('article')
      .should('have.length.greaterThan', 0)
    cy.visit(encodeURI('/tag/tag-d/'))
      .get('article')
      .should('have.length.greaterThan', 0)
    cy.visit(encodeURI('/tag/标签-1/'))
      .get('article')
      .should('have.length.greaterThan', 0)
    cy.visit(encodeURI('/tag/标签-2/'))
      .get('article')
      .should('have.length.greaterThan', 0)
  })
})
