import {
  ensureEndingSlash,
  isLinkAbsolute,
  isLinkWithProtocol,
} from '@vuepress/helper'

/** Nav item shared by the navbar and sidebar configs */
interface NavItem {
  text: string
  icon?: string
  prefix?: string
  link?: string
  children?: (NavItem | string)[]
}

type NavArray = (NavItem | string)[]

type NavConfig =
  | NavArray
  | Record<string, NavArray | 'heading' | false>
  | 'heading'
  | false

const resolvePrefix = (prefix: string, path: string): string =>
  isLinkAbsolute(path) || isLinkWithProtocol(path)
    ? path
    : `${ensureEndingSlash(prefix)}${path}`

const collectIcons = (
  items: NavArray,
  prefix: string,
  result: Map<string, string>,
): void => {
  for (const item of items) {
    if (typeof item === 'string') continue

    const childPrefix = item.prefix
      ? resolvePrefix(prefix, item.prefix)
      : prefix
    const path = item.link
      ? resolvePrefix(prefix, item.link)
      : item.prefix
        ? childPrefix
        : ''

    if (path && item.icon) result.set(path, item.icon)

    if (item.children) collectIcons(item.children, childPrefix, result)
  }
}

/**
 * Collect the page icons from the nav configs, so that pages which are not
 * present on the file system (e.g. the ones generated by `catalogPlugin`) can
 * reuse the icon of the matching nav item.
 *
 * @param navbars - Navbar configs
 * @param sidebars - Sidebar configs
 * @returns A map of page path to icon
 */
export const getNavIcons = (
  navbars: NavConfig[],
  sidebars: NavConfig[],
): Map<string, string> => {
  const result = new Map<string, string>()

  const collect = (config: NavConfig, prefix: string): void => {
    if (config === false || config === 'heading') return

    if (Array.isArray(config)) collectIcons(config, prefix, result)
    else
      for (const [base, items] of Object.entries(config)) collect(items, base)
  }

  for (const navbar of navbars) collect(navbar, '/')
  for (const sidebar of sidebars) collect(sidebar, '/')

  return result
}
