name: check

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build source files
        run: pnpm run bundle

      - name: Linter Test
        run: pnpm run lint:check

      - name: Docs Test
        run: |
          pnpm run --filter @vuepress/ecosystem-docs docs:build
          pnpm run --filter @vuepress/ecosystem-docs docs:build-webpack

      - name: Unit Test
        run: pnpm run test:unit
